/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package ru.milovtim.bondschedule


import spock.lang.Specification

import java.time.LocalDate

class BondTest extends Specification {


    def "create bond"() {
        setup:
        def bondBuilder = new Bond.BondBuilder()

        when:
        def bond = bondBuilder
                .issueDate(LocalDate.of(2020, 5, 15))
                .secId('RU000A1037L9')
                .build()

        then:
        bond.getSecId() == 'RU000A1037L9'
        bond.getIssueDate().dayOfMonth == 15
    }
}
